package vm

// Package vm implements the PHP virtual machine.
//
// This package will be implemented in Phase 3.
// See docs/phases/03-runtime-vm/ for implementation details.
//
// The VM executes bytecode instructions generated by the compiler.

// TODO: Implement in Phase 3
