package compiler

import (
	"fmt"
	"path/filepath"

	"github.com/krizos/php-go/pkg/ast"
	"github.com/krizos/php-go/pkg/lexer"
	"github.com/krizos/php-go/pkg/types"
	"github.com/krizos/php-go/pkg/vm"
)

// Compiler compiles PHP AST into VM bytecode
type Compiler struct {
	// instructions holds the generated bytecode
	instructions vm.Instructions

	// constants holds literal values referenced by the bytecode
	constants []interface{}

	// constantMap maps constant values to their indices for deduplication
	constantMap map[interface{}]int

	// symbolTable manages variable scopes
	symbolTable *SymbolTable

	// lastInstruction tracks the most recently emitted instruction
	lastInstruction EmittedInstruction

	// previousInstruction tracks the instruction before lastInstruction
	previousInstruction EmittedInstruction

	// loopStack tracks nested loops for break/continue
	loopStack []*LoopContext

	// tempVarStack tracks which temp variables are currently in use
	// The stack grows as we enter nested expressions
	tempVarStack []int

	// nextTempVar is the next available temp var number
	nextTempVar int
}

// LoopContext tracks information about a loop for break/continue
type LoopContext struct {
	// startPos is the position to jump to for continue
	startPos int

	// breakJumps holds positions of break statements to be patched
	breakJumps []int

	// continueJumps holds positions of continue statements to be patched
	continueJumps []int
}

// EmittedInstruction tracks metadata about an emitted instruction
type EmittedInstruction struct {
	Opcode   vm.Opcode
	Position int
}

// New creates a new compiler instance
func New() *Compiler {
	c := &Compiler{
		instructions:        vm.Instructions{},
		constants:           []interface{}{},
		constantMap:         make(map[interface{}]int),
		lastInstruction:     EmittedInstruction{},
		previousInstruction: EmittedInstruction{},
		tempVarStack:        []int{},
		nextTempVar:         0,
	}
	c.InitSymbolTable()
	return c
}

// ========================================
// Constant Table Management
// ========================================

// AddConstant adds a constant to the constant table
// Returns the index of the constant (reuses existing if duplicate)
func (c *Compiler) AddConstant(value interface{}) int {
	// Check if constant already exists
	if idx, ok := c.constantMap[value]; ok {
		return idx
	}

	// Add new constant
	idx := len(c.constants)
	c.constants = append(c.constants, value)
	c.constantMap[value] = idx
	return idx
}

// GetConstant retrieves a constant by index
func (c *Compiler) GetConstant(idx int) (interface{}, error) {
	if idx < 0 || idx >= len(c.constants) {
		return nil, fmt.Errorf("constant index out of bounds: %d", idx)
	}
	return c.constants[idx], nil
}

// Constants returns a copy of the constant table
func (c *Compiler) Constants() []interface{} {
	result := make([]interface{}, len(c.constants))
	copy(result, c.constants)
	return result
}

// ========================================
// Temp Variable Management
// ========================================

// AllocTemp allocates a new temp variable and returns its operand
// The temp variable is pushed onto the stack for proper nesting
func (c *Compiler) AllocTemp() vm.Operand {
	tempNum := c.nextTempVar
	c.tempVarStack = append(c.tempVarStack, tempNum)
	c.nextTempVar++
	return vm.TmpVarOperand(uint32(tempNum))
}

// FreeTemp deallocates the most recently allocated temp variable
// This pops the temp variable from the stack
func (c *Compiler) FreeTemp() {
	if len(c.tempVarStack) > 0 {
		// Pop from stack
		c.tempVarStack = c.tempVarStack[:len(c.tempVarStack)-1]
		// Reset nextTempVar when stack is empty to reuse temp vars
		if len(c.tempVarStack) == 0 {
			c.nextTempVar = 0
		}
	}
}

// CurrentTemp returns the currently active temp variable operand
// Returns TMPVAR(0) as fallback if no temp variables are allocated
func (c *Compiler) CurrentTemp() vm.Operand {
	if len(c.tempVarStack) > 0 {
		return vm.TmpVarOperand(uint32(c.tempVarStack[len(c.tempVarStack)-1]))
	}
	return vm.TmpVarOperand(0) // Fallback for backward compatibility
}

// ========================================
// Opcode Emission
// ========================================

// Emit emits an instruction with the given opcode and operands
// Returns the position of the emitted instruction
func (c *Compiler) Emit(opcode vm.Opcode, operands ...vm.Operand) int {
	return c.EmitWithLine(opcode, 0, operands...)
}

// EmitWithLine emits an instruction with line number information
// Returns the position of the emitted instruction
func (c *Compiler) EmitWithLine(opcode vm.Opcode, lineno uint32, operands ...vm.Operand) int {
	instr := vm.Instruction{
		Opcode: opcode,
		Lineno: lineno,
	}

	// Set operands based on count
	if len(operands) > 0 {
		instr.Op1 = operands[0]
	}
	if len(operands) > 1 {
		instr.Op2 = operands[1]
	}
	if len(operands) > 2 {
		instr.Result = operands[2]
	}

	pos := c.addInstruction(instr)

	// Update instruction tracking
	c.previousInstruction = c.lastInstruction
	c.lastInstruction = EmittedInstruction{
		Opcode:   opcode,
		Position: pos,
	}

	return pos
}

// EmitWithExtended emits an instruction with an extended value
func (c *Compiler) EmitWithExtended(opcode vm.Opcode, lineno uint32, extended uint32, operands ...vm.Operand) int {
	instr := vm.Instruction{
		Opcode:        opcode,
		Lineno:        lineno,
		ExtendedValue: extended,
	}

	// Set operands based on count
	if len(operands) > 0 {
		instr.Op1 = operands[0]
	}
	if len(operands) > 1 {
		instr.Op2 = operands[1]
	}
	if len(operands) > 2 {
		instr.Result = operands[2]
	}

	pos := c.addInstruction(instr)

	// Update instruction tracking
	c.previousInstruction = c.lastInstruction
	c.lastInstruction = EmittedInstruction{
		Opcode:   opcode,
		Position: pos,
	}

	return pos
}

// addInstruction adds an instruction to the instruction list
func (c *Compiler) addInstruction(instr vm.Instruction) int {
	pos := len(c.instructions)
	c.instructions = append(c.instructions, instr)
	return pos
}

// ========================================
// Instruction Manipulation
// ========================================

// ReplaceInstruction replaces the instruction at the given position
func (c *Compiler) ReplaceInstruction(pos int, instr vm.Instruction) error {
	if pos < 0 || pos >= len(c.instructions) {
		return fmt.Errorf("instruction position out of bounds: %d", pos)
	}
	c.instructions[pos] = instr
	return nil
}

// ChangeOperand changes an operand in an instruction at the given position
func (c *Compiler) ChangeOperand(pos int, operandNum int, operand vm.Operand) error {
	if pos < 0 || pos >= len(c.instructions) {
		return fmt.Errorf("instruction position out of bounds: %d", pos)
	}

	instr := c.instructions[pos]
	switch operandNum {
	case 1:
		instr.Op1 = operand
	case 2:
		instr.Op2 = operand
	case 3:
		instr.Result = operand
	default:
		return fmt.Errorf("invalid operand number: %d (must be 1, 2, or 3)", operandNum)
	}

	c.instructions[pos] = instr
	return nil
}

// CurrentPosition returns the position where the next instruction will be emitted
func (c *Compiler) CurrentPosition() int {
	return len(c.instructions)
}

// LastInstructionIs checks if the last instruction is the given opcode
func (c *Compiler) LastInstructionIs(opcode vm.Opcode) bool {
	return c.lastInstruction.Opcode == opcode
}

// RemoveLastInstruction removes the last emitted instruction
// Used for optimizations (e.g., removing unnecessary OpPop)
func (c *Compiler) RemoveLastInstruction() {
	if len(c.instructions) == 0 {
		return
	}

	c.instructions = c.instructions[:c.lastInstruction.Position]
	c.lastInstruction = c.previousInstruction
}

// ========================================
// Program Assembly
// ========================================

// Bytecode represents the compiled bytecode program
type Bytecode struct {
	Instructions vm.Instructions
	Constants    []interface{}
	NumCVs       int // Number of compiled variables (for proper TMPVAR offset)
}

// Bytecode assembles and returns the final compiled bytecode
func (c *Compiler) Bytecode() *Bytecode {
	return &Bytecode{
		Instructions: c.instructions,
		Constants:    c.constants,
		NumCVs:       c.symbolTable.NumDefinitions(),
	}
}

// ========================================
// Compilation Entry Point
// ========================================

// Compile compiles an AST program into bytecode
func (c *Compiler) Compile(node ast.Node) error {
	switch node := node.(type) {
	case *ast.Program:
		for _, stmt := range node.Statements {
			if err := c.Compile(stmt); err != nil {
				return err
			}
		}
		return nil

	// Statements
	case *ast.ExpressionStatement:
		if err := c.Compile(node.Expression); err != nil {
			return err
		}
		// Free all temp variables allocated by this expression
		// Expression result is in CurrentTemp(), free it
		if len(c.tempVarStack) > 0 {
			c.Emit(vm.OpFree, c.CurrentTemp())
			// Free all temps used by the expression
			for len(c.tempVarStack) > 0 {
				c.FreeTemp()
			}
		}
		return nil

	case *ast.BlockStatement:
		for i, stmt := range node.Statements {
			if err := c.Compile(stmt); err != nil {
				return err
			}

			// Optimization: Dead code elimination
			// Stop compiling after a return statement (code after return is unreachable)
			if _, isReturn := stmt.(*ast.ReturnStatement); isReturn {
				// Skip remaining statements in this block
				if i < len(node.Statements)-1 {
					// There is unreachable code after the return
					// For now, we silently skip it (could add a warning in the future)
					break
				}
			}
		}
		return nil

	case *ast.EchoStatement:
		for _, expr := range node.Expressions {
			if err := c.Compile(expr); err != nil {
				return err
			}
			// Emit ECHO instruction for each expression - value is in CurrentTemp()
			c.EmitWithLine(vm.OpEcho, uint32(node.Token.Pos.Line), c.CurrentTemp())
		}
		return nil

	case *ast.ReturnStatement:
		if node.ReturnValue != nil {
			if err := c.Compile(node.ReturnValue); err != nil {
				return err
			}
			c.EmitWithLine(vm.OpReturn, uint32(node.Token.Pos.Line), c.CurrentTemp())
		} else {
			// Return null
			c.EmitWithLine(vm.OpReturn, uint32(node.Token.Pos.Line))
		}
		return nil

	case *ast.GlobalStatement:
		// Emit BIND_GLOBAL for each variable
		for _, variable := range node.Variables {
			// Get or create the variable symbol
			symbol := c.symbolTable.Define(variable.Value)

			// Emit BIND_GLOBAL opcode
			// This tells the VM to bind the local variable to the global scope
			c.EmitWithLine(vm.OpBindGlobal, uint32(node.Token.Pos.Line),
				vm.CVOperand(uint32(symbol.Index)),
				vm.UnusedOperand(),
				vm.UnusedOperand())
		}
		return nil

	case *ast.NamespaceStatement:
		// Namespace declarations are compile-time constructs that affect name resolution
		// For now, we'll compile the body statements but namespace resolution
		// is handled by the symbol table and name resolution logic
		if node.Body != nil {
			// Bracketed namespace: namespace Name { ... }
			for _, stmt := range node.Body.Statements {
				if err := c.Compile(stmt); err != nil {
					return err
				}
			}
		} else {
			// Unbracketed namespace: namespace Name; statements...
			for _, stmt := range node.Statements {
				if err := c.Compile(stmt); err != nil {
					return err
				}
			}
		}
		return nil

	case *ast.UseStatement:
		// Use statements are compile-time constructs that affect name resolution
		// The imports are registered in the symbol table during compilation
		// No runtime opcodes need to be emitted
		// TODO: Register use imports in symbol table for proper name resolution
		return nil

	case *ast.UnsetStatement:
		// Emit UNSET_* for each variable
		for _, variable := range node.Variables {
			// Determine the type of variable expression
			switch v := variable.(type) {
			case *ast.Variable:
				// Simple variable: unset($var)
				symbol, ok := c.ResolveVariable(v.Name)
				if !ok {
					return fmt.Errorf("undefined variable: %s", v.Name)
				}
				c.EmitWithLine(vm.OpUnsetVar, uint32(node.Token.Pos.Line),
					vm.CVOperand(uint32(symbol.Index)),
					vm.UnusedOperand(),
					vm.UnusedOperand())

			case *ast.IndexExpression:
				// Array element: unset($arr[$key])
				// First compile the array expression
				if err := c.Compile(v.Left); err != nil {
					return err
				}
				arrayTemp := c.CurrentTemp()

				// Then compile the index expression
				if err := c.Compile(v.Index); err != nil {
					return err
				}
				indexTemp := c.CurrentTemp()

				// Emit UNSET_DIM
				c.EmitWithLine(vm.OpUnsetDim, uint32(node.Token.Pos.Line),
					arrayTemp,
					indexTemp,
					vm.UnusedOperand())

				c.FreeTemp()
				c.FreeTemp()

			case *ast.PropertyExpression:
				// Object property: unset($obj->prop)
				// First compile the object expression
				if err := c.Compile(v.Object); err != nil {
					return err
				}
				objectTemp := c.CurrentTemp()

				// Get property name (Property is an Identifier)
				propName := ""
				if ident, ok := v.Property.(*ast.Identifier); ok {
					propName = ident.Value
				} else {
					return fmt.Errorf("property name must be an identifier")
				}
				propIdx := c.AddConstant(types.NewString(propName))

				// Emit UNSET_OBJ
				c.EmitWithLine(vm.OpUnsetObj, uint32(node.Token.Pos.Line),
					objectTemp,
					vm.ConstOperand(uint32(propIdx)),
					vm.UnusedOperand())

				c.FreeTemp()

			default:
				return fmt.Errorf("invalid expression in unset(): %T", variable)
			}
		}
		return nil

	// Literals
	case *ast.IntegerLiteral:
		constIdx := c.AddConstant(node.Value)
		temp := c.AllocTemp()
		c.EmitWithLine(vm.OpQMAssign, uint32(node.Token.Pos.Line),
			vm.ConstOperand(uint32(constIdx)),
			vm.UnusedOperand(),
			temp)
		return nil

	case *ast.FloatLiteral:
		constIdx := c.AddConstant(node.Value)
		temp := c.AllocTemp()
		c.EmitWithLine(vm.OpQMAssign, uint32(node.Token.Pos.Line),
			vm.ConstOperand(uint32(constIdx)),
			vm.UnusedOperand(),
			temp)
		return nil

	case *ast.StringLiteral:
		constIdx := c.AddConstant(node.Value)
		temp := c.AllocTemp()
		c.EmitWithLine(vm.OpQMAssign, uint32(node.Token.Pos.Line),
			vm.ConstOperand(uint32(constIdx)),
			vm.UnusedOperand(),
			temp)
		return nil

	// Interpolated String - compile as series of concatenations
	case *ast.InterpolatedStringExpression:
		if len(node.Parts) == 0 {
			// Empty interpolated string - just return empty string
			constIdx := c.AddConstant("")
			temp := c.AllocTemp()
			c.EmitWithLine(vm.OpQMAssign, uint32(node.Token.Pos.Line),
				vm.ConstOperand(uint32(constIdx)),
				vm.UnusedOperand(),
				temp)
			return nil
		}

		// Compile first part
		if err := c.Compile(node.Parts[0]); err != nil {
			return err
		}
		// Result is in CurrentTemp()
		previousTemp := c.CurrentTemp()

		// Concatenate remaining parts
		for i := 1; i < len(node.Parts); i++ {
			// Compile next part
			if err := c.Compile(node.Parts[i]); err != nil {
				return err
			}
			currentTemp := c.CurrentTemp()

			// Concatenate: previous . current -> result
			resultTemp := c.AllocTemp()
			c.EmitWithLine(vm.OpConcat, uint32(node.Token.Pos.Line),
				previousTemp,
				currentTemp,
				resultTemp)
			previousTemp = resultTemp
		}

		return nil

	case *ast.BooleanLiteral:
		constIdx := c.AddConstant(node.Value)
		temp := c.AllocTemp()
		c.EmitWithLine(vm.OpQMAssign, uint32(node.Token.Pos.Line),
			vm.ConstOperand(uint32(constIdx)),
			vm.UnusedOperand(),
			temp)
		return nil

	case *ast.NullLiteral:
		constIdx := c.AddConstant(nil)
		temp := c.AllocTemp()
		c.EmitWithLine(vm.OpQMAssign, uint32(node.Token.Pos.Line),
			vm.ConstOperand(uint32(constIdx)),
			vm.UnusedOperand(),
			temp)
		return nil

	case *ast.MagicConstant:
		// Magic constants will be resolved at compile time where possible
		var value interface{}
		switch node.Kind {
		case lexer.LINE_CONST:
			value = int64(node.Token.Pos.Line)
		case lexer.FILE_CONST:
			value = node.Token.Pos.Filename
		case lexer.DIR_CONST:
			// Get directory of the file
			if node.Token.Pos.Filename != "" {
				value = filepath.Dir(node.Token.Pos.Filename)
			} else {
				value = ""
			}
		case lexer.FUNCTION_CONST:
			value = "" // Will be set by runtime based on current function
		case lexer.CLASS_CONST:
			value = "" // Will be set by runtime based on current class
		case lexer.TRAIT_CONST:
			value = "" // Will be set by runtime based on current trait
		case lexer.METHOD_CONST:
			value = "" // Will be set by runtime based on current method
		case lexer.NAMESPACE_CONST:
			value = "" // Will be set by runtime based on current namespace
		default:
			value = node.Token.Literal
		}

		constIdx := c.AddConstant(value)
		temp := c.AllocTemp()
		c.EmitWithLine(vm.OpQMAssign, uint32(node.Token.Pos.Line),
			vm.ConstOperand(uint32(constIdx)),
			vm.UnusedOperand(),
			temp)
		return nil

	// Infix Expressions (binary operators)
	case *ast.InfixExpression:
		// Optimization: Constant folding
		// If both operands are constant literals, evaluate at compile time
		if isConstantLiteral(node.Left) && isConstantLiteral(node.Right) {
			leftVal, _ := getConstantValue(node.Left)
			rightVal, _ := getConstantValue(node.Right)

			if result, ok := foldConstantBinaryOp(leftVal, rightVal, node.Operator); ok {
				// Emit a single constant instead of the operation
				constIdx := c.AddConstant(result)
				temp := c.AllocTemp()
				c.EmitWithLine(vm.OpQMAssign, uint32(node.Token.Pos.Line),
					vm.ConstOperand(uint32(constIdx)),
					vm.UnusedOperand(),
					temp)
				return nil
			}
		}

		// Optimization: Strength reduction
		// Replace expensive operations with cheaper equivalents
		if optimized, err := c.applyStrengthReduction(node); optimized {
			return err
		}

		// Normal compilation if not foldable or reducible
		// Use temp variable stack to handle nested expressions properly

		// Compile left operand - it will allocate temps and leave result in CurrentTemp()
		if err := c.Compile(node.Left); err != nil {
			return err
		}
		// Capture left result immediately before Right compilation can overwrite CurrentTemp
		leftTemp := c.CurrentTemp()

		// Compile right operand - it will allocate more temps and leave result in CurrentTemp()
		if err := c.Compile(node.Right); err != nil {
			return err
		}
		// Right result is in CurrentTemp()
		rightTemp := c.CurrentTemp()

		// Emit the appropriate opcode based on operator
		var opcode vm.Opcode
		switch node.Operator {
		case "+":
			opcode = vm.OpAdd
		case "-":
			opcode = vm.OpSub
		case "*":
			opcode = vm.OpMul
		case "/":
			opcode = vm.OpDiv
		case "%":
			opcode = vm.OpMod
		case "**":
			opcode = vm.OpPow
		case ".":
			opcode = vm.OpConcat
		case "==":
			opcode = vm.OpIsEqual
		case "!=":
			opcode = vm.OpIsNotEqual
		case "===":
			opcode = vm.OpIsIdentical
		case "!==":
			opcode = vm.OpIsNotIdentical
		case "<":
			opcode = vm.OpIsSmaller
		case "<=":
			opcode = vm.OpIsSmallerOrEqual
		case ">":
			// Swap operands and use IS_SMALLER
			opcode = vm.OpIsSmaller
			leftTemp, rightTemp = rightTemp, leftTemp
		case ">=":
			// Swap operands and use IS_SMALLER_OR_EQUAL
			opcode = vm.OpIsSmallerOrEqual
			leftTemp, rightTemp = rightTemp, leftTemp
		case "|":
			opcode = vm.OpBWOr
		case "&":
			opcode = vm.OpBWAnd
		case "^":
			opcode = vm.OpBWXor
		case "<<":
			opcode = vm.OpSL
		case ">>":
			opcode = vm.OpSR
		case "<=>":
			opcode = vm.OpSpaceship
		default:
			return fmt.Errorf("unknown infix operator: %s", node.Operator)
		}

		// Emit operation with result going to a new temp
		resultTemp := c.AllocTemp()
		c.EmitWithLine(opcode, uint32(node.Token.Pos.Line),
			leftTemp,
			rightTemp,
			resultTemp)

		return nil

	// Prefix Expressions (unary operators)
	case *ast.PrefixExpression:
		// Optimization: Constant folding for unary operations
		if isConstantLiteral(node.Right) {
			operandVal, _ := getConstantValue(node.Right)

			if result, ok := foldConstantUnaryOp(operandVal, node.Operator); ok {
				// Emit a single constant instead of the operation
				constIdx := c.AddConstant(result)
				temp := c.AllocTemp()
				c.EmitWithLine(vm.OpQMAssign, uint32(node.Token.Pos.Line),
					vm.ConstOperand(uint32(constIdx)),
					vm.UnusedOperand(),
					temp)
				return nil
			}
		}

		// Normal compilation if not foldable
		// Compile operand
		if err := c.Compile(node.Right); err != nil {
			return err
		}
		operandTemp := c.CurrentTemp()

		// Emit the appropriate opcode with result temp
		resultTemp := c.AllocTemp()
		var opcode vm.Opcode
		switch node.Operator {
		case "!":
			opcode = vm.OpBoolNot
		case "-":
			// Unary minus: 0 - operand
			constIdx := c.AddConstant(int64(0))
			c.EmitWithLine(vm.OpSub, uint32(node.Token.Pos.Line),
				vm.ConstOperand(uint32(constIdx)),
				operandTemp,
				resultTemp)
			return nil
		case "~":
			opcode = vm.OpBWNot
		case "++(postfix)", "--(postfix)":
			// Postfix increment/decrement: evaluate to current value, then modify variable
			// Result is the OLD value (operandTemp), but we must modify the variable
			// operandTemp already contains the current value from compiling node.Right

			// Get variable from Right (should be a Variable node)
			varNode, ok := node.Right.(*ast.Variable)
			if !ok {
				return fmt.Errorf("postfix %s requires a variable", node.Operator)
			}

			// Look up the variable
			symbol, ok := c.ResolveVariable(varNode.Name)
			if !ok {
				symbol = c.DefineVariable(varNode.Name)
			}

			// Allocate temp for modified value first
			modTemp := c.AllocTemp()

			// Create constant 1
			oneIdx := c.AddConstant(int64(1))

			// Increment/decrement into modTemp
			if node.Operator == "++(postfix)" {
				c.EmitWithLine(vm.OpAdd, uint32(node.Token.Pos.Line),
					operandTemp,
					vm.ConstOperand(uint32(oneIdx)),
					modTemp)
			} else {
				c.EmitWithLine(vm.OpSub, uint32(node.Token.Pos.Line),
					operandTemp,
					vm.ConstOperand(uint32(oneIdx)),
					modTemp)
			}

			// Assign modified value back to variable
			switch symbol.Scope {
			case GlobalScope:
				c.EmitWithLine(vm.OpAssign, uint32(node.Token.Pos.Line),
					modTemp,
					vm.UnusedOperand(),
					vm.CVOperand(uint32(symbol.Index)))
			case LocalScope:
				c.EmitWithLine(vm.OpQMAssign, uint32(node.Token.Pos.Line),
					modTemp,
					vm.UnusedOperand(),
					vm.CVOperand(uint32(symbol.Index)))
			}

			// Now allocate resultTemp and save old value (this becomes CurrentTemp)
			resultTemp := c.AllocTemp()
			c.EmitWithLine(vm.OpQMAssign, uint32(node.Token.Pos.Line),
				operandTemp,
				vm.UnusedOperand(),
				resultTemp)

			// resultTemp has the old value (correct for postfix) and is CurrentTemp
			return nil
		case "++", "--":
			// Prefix increment/decrement: modify variable and return new value
			// Get variable from Right (should be a Variable node)
			varNode, ok := node.Right.(*ast.Variable)
			if !ok {
				return fmt.Errorf("prefix %s requires a variable", node.Operator)
			}

			// Look up the variable
			symbol, ok := c.ResolveVariable(varNode.Name)
			if !ok {
				symbol = c.DefineVariable(varNode.Name)
			}

			// Create constant 1
			oneIdx := c.AddConstant(int64(1))

			// Increment/decrement the variable
			if node.Operator == "++" {
				c.EmitWithLine(vm.OpAdd, uint32(node.Token.Pos.Line),
					operandTemp,
					vm.ConstOperand(uint32(oneIdx)),
					resultTemp)
			} else {
				c.EmitWithLine(vm.OpSub, uint32(node.Token.Pos.Line),
					operandTemp,
					vm.ConstOperand(uint32(oneIdx)),
					resultTemp)
			}

			// Assign back to variable
			switch symbol.Scope {
			case GlobalScope:
				c.EmitWithLine(vm.OpAssign, uint32(node.Token.Pos.Line),
					resultTemp,
					vm.UnusedOperand(),
					vm.CVOperand(uint32(symbol.Index)))
			case LocalScope:
				c.EmitWithLine(vm.OpQMAssign, uint32(node.Token.Pos.Line),
					resultTemp,
					vm.UnusedOperand(),
					vm.CVOperand(uint32(symbol.Index)))
			}

			// resultTemp has the new value
			return nil
		default:
			return fmt.Errorf("unknown prefix operator: %s", node.Operator)
		}

		c.EmitWithLine(opcode, uint32(node.Token.Pos.Line),
			operandTemp,
			vm.UnusedOperand(),
			resultTemp)
		return nil

	case *ast.Variable:
		// Look up the variable in the symbol table
		symbol, ok := c.ResolveVariable(node.Name)
		if !ok {
			// Variable not defined, define it now (PHP allows implicit declaration)
			symbol = c.DefineVariable(node.Name)
		}

		// Emit FETCH instruction based on scope
		temp := c.AllocTemp()
		switch symbol.Scope {
		case GlobalScope:
			// Fetch global variable
			c.EmitWithLine(vm.OpFetchR, uint32(node.Token.Pos.Line),
				vm.CVOperand(uint32(symbol.Index)),
				vm.UnusedOperand(),
				temp)
		case LocalScope:
			// Fetch local variable (compiled variable for direct access)
			c.EmitWithLine(vm.OpQMAssign, uint32(node.Token.Pos.Line),
				vm.CVOperand(uint32(symbol.Index)),
				vm.UnusedOperand(),
				temp)
		case BuiltinScope:
			return fmt.Errorf("cannot use builtin '%s' as variable", node.Name)
		case FreeScope:
			// Fetch free variable (closure variable)
			c.EmitWithLine(vm.OpFetchR, uint32(node.Token.Pos.Line),
				vm.CVOperand(uint32(symbol.Index)),
				vm.UnusedOperand(),
				temp)
		}
		return nil

	case *ast.AssignmentExpression:
		// Compile the right side first
		if err := c.Compile(node.Right); err != nil {
			return err
		}

		// Handle the left side (variable)
		if variable, ok := node.Left.(*ast.Variable); ok {
			// Look up or define the variable
			symbol, ok := c.ResolveVariable(variable.Name)
			if !ok {
				symbol = c.DefineVariable(variable.Name)
			}

			// Emit ASSIGN instruction - value is in CurrentTemp() after compiling Right
			c.EmitWithLine(vm.OpAssign, uint32(node.Token.Pos.Line),
				c.CurrentTemp(), // Value from right-hand side
				vm.UnusedOperand(),
				vm.CVOperand(uint32(symbol.Index))) // Store in compiled variable
			return nil
		}

		// Handle property assignment: $obj->prop = value
		if property, ok := node.Left.(*ast.PropertyExpression); ok {
			// Value is already compiled - capture it now before compiling object/property
			valueTemp := c.CurrentTemp()

			// Compile the object
			if err := c.Compile(property.Object); err != nil {
				return err
			}
			objTemp := c.CurrentTemp()

			// Compile the property (could be identifier or dynamic expression)
			if err := c.Compile(property.Property); err != nil {
				return err
			}
			propTemp := c.CurrentTemp()

			// Emit ASSIGN_OBJ instruction
			c.EmitWithLine(vm.OpAssignObj, uint32(node.Token.Pos.Line),
				objTemp,   // Object
				propTemp,  // Property name
				valueTemp) // Value to assign
			return nil
		}

		// Handle array element assignment: $arr[index] = value
		if index, ok := node.Left.(*ast.IndexExpression); ok {
			// Value is already compiled - capture it now before compiling array/index
			valueTemp := c.CurrentTemp()

			// Compile the array variable
			if err := c.Compile(index.Left); err != nil {
				return err
			}
			arrayTemp := c.CurrentTemp()

			// Compile the index
			if err := c.Compile(index.Index); err != nil {
				return err
			}
			indexTemp := c.CurrentTemp()

			// Emit ASSIGN_DIM instruction
			c.EmitWithLine(vm.OpAssignDim, uint32(node.Token.Pos.Line),
				arrayTemp, // Array
				indexTemp, // Index/key
				valueTemp) // Value to assign
			return nil
		}
		return fmt.Errorf("assignment to non-variable not yet implemented")

	// Identifier (convert to string constant)
	case *ast.Identifier:
		constIdx := c.AddConstant(node.Value)
		temp := c.AllocTemp()
		c.EmitWithLine(vm.OpQMAssign, uint32(node.Token.Pos.Line),
			vm.ConstOperand(uint32(constIdx)),
			vm.UnusedOperand(),
			temp)
		return nil

	// Grouped Expression (just compile the inner expression)
	case *ast.GroupedExpression:
		return c.Compile(node.Expr)

	// Closure Expression (anonymous function)
	case *ast.ClosureExpression:
		// Remember closure start position
		closureStart := c.CurrentPosition()

		// Enter new scope for closure
		c.EnterScope()

		// Emit RECV opcodes for each parameter
		for i, param := range node.Parameters {
			// Define parameter variable in closure scope
			symbol := c.DefineVariable(param.Name.Name)

			// Add parameter index to constants pool
			paramIdxConst := c.AddConstant(int64(i))

			if param.Variadic {
				// RECV_VARIADIC for ...args
				c.EmitWithLine(vm.OpRecvVariadic, uint32(node.Token.Pos.Line),
					vm.ConstOperand(uint32(paramIdxConst)), // Parameter index
					vm.UnusedOperand(),
					vm.CVOperand(uint32(symbol.Index))) // Store in compiled variable
			} else if param.DefaultValue != nil {
				// RECV_INIT for parameters with defaults
				// Compile default value
				if err := c.Compile(param.DefaultValue); err != nil {
					return err
				}

				c.EmitWithLine(vm.OpRecvInit, uint32(node.Token.Pos.Line),
					vm.ConstOperand(uint32(paramIdxConst)), // Parameter index
					vm.TmpVarOperand(0),                    // Default value in temp 0
					vm.CVOperand(uint32(symbol.Index)))     // Store in compiled variable
			} else {
				// RECV for required parameters
				recvOp := vm.OpRecv
				if param.ByRef {
					recvOp = vm.OpSendRef // Use SEND_REF for by-reference parameters
				}

				c.EmitWithLine(recvOp, uint32(node.Token.Pos.Line),
					vm.ConstOperand(uint32(paramIdxConst)), // Parameter index
					vm.UnusedOperand(),
					vm.CVOperand(uint32(symbol.Index))) // Store in compiled variable
			}
		}

		// Compile closure body
		if err := c.Compile(node.Body); err != nil {
			return err
		}

		// Add implicit return if closure doesn't end with return
		if !c.LastInstructionIs(vm.OpReturn) && !c.LastInstructionIs(vm.OpReturnByRef) {
			// Return null
			c.EmitWithLine(vm.OpReturn, uint32(node.Token.Pos.Line),
				vm.UnusedOperand(),
				vm.UnusedOperand(),
				vm.UnusedOperand())
		}

		// Exit closure scope
		c.ExitScope()

		// Closure end position
		closureEnd := c.CurrentPosition()

		// DECLARE_LAMBDA_FUNCTION to create the closure object
		// Store closure metadata: num params, start pos, end pos, flags
		flags := uint32(0)
		if node.Static {
			flags |= 1 // Static flag
		}
		if node.ByRef {
			flags |= 2 // Return by reference flag
		}

		c.EmitWithExtended(vm.OpDeclareLambdaFunction, uint32(node.Token.Pos.Line),
			uint32(len(node.Parameters)),          // Number of parameters
			vm.ConstOperand(uint32(flags)),        // Flags (static, byref)
			vm.ConstOperand(uint32(closureStart)), // Closure start position
			vm.ConstOperand(uint32(closureEnd)))   // Closure end position

		// Bind captured variables from use clause
		for _, useVar := range node.Use {
			// Get the variable from parent scope
			varNameIdx := c.AddConstant(useVar.Variable.Name)
			byRefFlag := uint32(0)
			if useVar.ByRef {
				byRefFlag = 1
			}

			c.EmitWithLine(vm.OpBindLexical, uint32(node.Token.Pos.Line),
				vm.ConstOperand(uint32(varNameIdx)), // Variable name
				vm.ConstOperand(byRefFlag),          // By reference flag
				vm.TmpVarOperand(0))                 // Closure object in temp 0
		}

		return nil

	// Arrow Function Expression (PHP 7.4+)
	case *ast.ArrowFunctionExpression:
		// Remember arrow function start position
		arrowStart := c.CurrentPosition()

		// Find all variables referenced in the arrow function body
		// We'll need to capture these from the parent scope
		referencedVars := findReferencedVariables(node.Body)

		// Filter out parameters - they're defined in the arrow function scope
		paramNames := make(map[string]bool)
		for _, param := range node.Parameters {
			paramNames[param.Name.Name] = true
		}

		// Variables to capture (referenced but not parameters)
		captureVars := make([]string, 0)
		for _, varName := range referencedVars {
			if !paramNames[varName] {
				// Check if variable exists in parent scope
				if _, ok := c.symbolTable.Resolve(varName); ok {
					captureVars = append(captureVars, varName)
				}
			}
		}

		// Enter new scope for arrow function
		c.EnterScope()

		// Emit RECV opcodes for each parameter
		for i, param := range node.Parameters {
			// Define parameter variable in arrow function scope
			symbol := c.DefineVariable(param.Name.Name)

			// Add parameter index to constants pool
			paramIdxConst := c.AddConstant(int64(i))

			if param.Variadic {
				c.EmitWithLine(vm.OpRecvVariadic, uint32(node.Token.Pos.Line),
					vm.ConstOperand(uint32(paramIdxConst)),
					vm.UnusedOperand(),
					vm.CVOperand(uint32(symbol.Index)))
			} else if param.DefaultValue != nil {
				if err := c.Compile(param.DefaultValue); err != nil {
					return err
				}
				c.EmitWithLine(vm.OpRecvInit, uint32(node.Token.Pos.Line),
					vm.ConstOperand(uint32(paramIdxConst)),
					vm.TmpVarOperand(0),
					vm.CVOperand(uint32(symbol.Index)))
			} else {
				recvOp := vm.OpRecv
				if param.ByRef {
					recvOp = vm.OpSendRef
				}
				c.EmitWithLine(recvOp, uint32(node.Token.Pos.Line),
					vm.ConstOperand(uint32(paramIdxConst)),
					vm.UnusedOperand(),
					vm.CVOperand(uint32(symbol.Index)))
			}
		}

		// Compile the body expression
		if err := c.Compile(node.Body); err != nil {
			return err
		}

		// Arrow functions implicitly return the expression value
		returnOp := vm.OpReturn
		if node.ByRef {
			returnOp = vm.OpReturnByRef
		}
		c.EmitWithLine(returnOp, uint32(node.Token.Pos.Line),
			vm.TmpVarOperand(0), // Return value from expression
			vm.UnusedOperand(),
			vm.UnusedOperand())

		// Exit arrow function scope
		c.ExitScope()

		// Arrow function end position
		arrowEnd := c.CurrentPosition()

		// DECLARE_LAMBDA_FUNCTION to create the arrow function object
		flags := uint32(0)
		if node.Static {
			flags |= 1 // Static flag
		}
		if node.ByRef {
			flags |= 2 // Return by reference flag
		}

		c.EmitWithExtended(vm.OpDeclareLambdaFunction, uint32(node.Token.Pos.Line),
			uint32(len(node.Parameters)),        // Number of parameters
			vm.ConstOperand(uint32(flags)),      // Flags (static, byref)
			vm.ConstOperand(uint32(arrowStart)), // Arrow function start position
			vm.ConstOperand(uint32(arrowEnd)))   // Arrow function end position

		// Arrow functions auto-capture variables from parent scope
		// Emit BIND_LEXICAL for each captured variable
		// Note: Arrow functions capture by value (not by reference)
		for _, varName := range captureVars {
			// Add variable name as constant
			nameIdx := c.AddConstant(varName)

			// Emit BIND_LEXICAL to capture the variable
			// Op1: variable name (constant)
			// Op2: by-reference flag (0 for by-value)
			// Result: closure object (from previous DECLARE_LAMBDA_FUNCTION)
			c.EmitWithLine(vm.OpBindLexical, uint32(node.Token.Pos.Line),
				vm.ConstOperand(uint32(nameIdx)), // Variable name
				vm.ConstOperand(0),               // By-value (0 = false)
				vm.TmpVarOperand(0))              // Closure in temp var 0
		}

		return nil

	// Array Literal
	case *ast.ArrayExpression:
		// Allocate temp for the array and initialize it
		arrayTemp := c.AllocTemp()
		c.EmitWithLine(vm.OpInitArray, uint32(node.Token.Pos.Line),
			vm.UnusedOperand(),
			vm.UnusedOperand(),
			arrayTemp)

		// Add elements to array
		for _, elem := range node.Elements {
			// Compile the value
			if err := c.Compile(elem.Value); err != nil {
				return err
			}
			valueTemp := c.CurrentTemp()

			// If there's a key, compile it
			if elem.Key != nil {
				if err := c.Compile(elem.Key); err != nil {
					return err
				}
				keyTemp := c.CurrentTemp()

				// ADD_ARRAY_ELEMENT with key: array[key] = value
				c.EmitWithLine(vm.OpAddArrayElement, uint32(node.Token.Pos.Line),
					valueTemp,
					keyTemp,
					arrayTemp)

				// Free the key temp
				c.FreeTemp()
			} else {
				// ADD_ARRAY_ELEMENT without key: array[] = value
				c.EmitWithLine(vm.OpAddArrayElement, uint32(node.Token.Pos.Line),
					valueTemp,
					vm.UnusedOperand(),
					arrayTemp)
			}

			// Free the value temp
			c.FreeTemp()
		}
		return nil

	// Array Access
	case *ast.IndexExpression:
		// Compile the array/string
		if err := c.Compile(node.Left); err != nil {
			return err
		}
		arrayTemp := c.CurrentTemp()

		// Compile the index
		if err := c.Compile(node.Index); err != nil {
			return err
		}
		indexTemp := c.CurrentTemp()

		// Allocate result temp and emit FETCH_DIM_R: result = array[index]
		resultTemp := c.AllocTemp()
		c.EmitWithLine(vm.OpFetchDimR, uint32(node.Token.Pos.Line),
			arrayTemp,
			indexTemp,
			resultTemp)
		return nil

	// Property Access
	case *ast.PropertyExpression:
		// Compile the object
		if err := c.Compile(node.Object); err != nil {
			return err
		}
		objTemp := c.CurrentTemp()

		// Compile the property (could be identifier or dynamic expression)
		if err := c.Compile(node.Property); err != nil {
			return err
		}
		propTemp := c.CurrentTemp()

		// Allocate result temp and emit FETCH_OBJ_R: result = obj->prop
		resultTemp := c.AllocTemp()
		c.EmitWithLine(vm.OpFetchObjR, uint32(node.Token.Pos.Line),
			objTemp,
			propTemp,
			resultTemp)
		return nil

	// Function Call
	case *ast.CallExpression:
		// Check if this is a special language construct (exit/die)
		if ident, ok := node.Function.(*ast.Identifier); ok {
			funcName := ident.Value
			if funcName == "exit" || funcName == "die" {
				// Handle exit/die specially
				if len(node.Arguments) > 0 {
					// Compile the argument (exit message/code)
					if err := c.Compile(node.Arguments[0].Value); err != nil {
						return err
					}
					c.EmitWithLine(vm.OpExit, uint32(node.Token.Pos.Line), c.CurrentTemp())
				} else {
					// No argument, just exit
					c.EmitWithLine(vm.OpExit, uint32(node.Token.Pos.Line), vm.UnusedOperand())
				}
				return nil
			}
		}

		// Compile the function expression - it will allocate a temp
		if err := c.Compile(node.Function); err != nil {
			return err
		}
		funcTemp := c.CurrentTemp()

		// KEY INSIGHT: Compile ALL arguments BEFORE initializing the call
		// This allows nested calls in arguments to complete fully before we init this call
		var argTemps []vm.Operand
		for _, arg := range node.Arguments {
			if err := c.Compile(arg.Value); err != nil {
				return err
			}
			// Save the argument's temp - it's in CurrentTemp() after compilation
			argTemps = append(argTemps, c.CurrentTemp())
		}

		// NOW initialize the function call (after all arguments are ready)
		c.EmitWithLine(vm.OpInitFcallByName, uint32(node.Token.Pos.Line),
			funcTemp,
			vm.ConstOperand(uint32(len(node.Arguments))), // Argument count
			vm.UnusedOperand())

		// Send all the pre-compiled arguments
		for _, argTemp := range argTemps {
			c.EmitWithLine(vm.OpSendVal, uint32(node.Token.Pos.Line),
				argTemp,
				vm.UnusedOperand(),
				vm.UnusedOperand())
		}

		// Execute function call - result goes to a new temp
		resultTemp := c.AllocTemp()
		c.EmitWithLine(vm.OpDoFcall, uint32(node.Token.Pos.Line),
			vm.UnusedOperand(),
			vm.UnusedOperand(),
			resultTemp)
		return nil

	// Method Call
	case *ast.MethodCallExpression:
		// Compile the object
		if err := c.Compile(node.Object); err != nil {
			return err
		}
		objTemp := c.CurrentTemp()

		// Compile the method name (could be identifier or dynamic)
		if err := c.Compile(node.Method); err != nil {
			return err
		}
		methodTemp := c.CurrentTemp()

		// Compile arguments
		for _, arg := range node.Arguments {
			if err := c.Compile(arg.Value); err != nil {
				return err
			}
			// TODO: Push arguments onto stack properly
		}

		// Initialize method call
		c.EmitWithLine(vm.OpInitMethodCall, uint32(node.Token.Pos.Line),
			objTemp,
			methodTemp,
			vm.UnusedOperand())

		// Allocate result temp and execute method call with argument count in extended value
		resultTemp := c.AllocTemp()
		c.EmitWithExtended(vm.OpDoFcall, uint32(node.Token.Pos.Line),
			uint32(len(node.Arguments)),
			vm.UnusedOperand(),
			vm.UnusedOperand(),
			resultTemp)
		return nil

	// Static Property Access (Class::$property)
	case *ast.StaticPropertyExpression:
		// Compile the class name (could be identifier or dynamic)
		if err := c.Compile(node.Class); err != nil {
			return err
		}
		classTemp := c.CurrentTemp()

		// Compile the property (usually a variable)
		if err := c.Compile(node.Property); err != nil {
			return err
		}
		propTemp := c.CurrentTemp()

		// Allocate result temp and fetch static property
		resultTemp := c.AllocTemp()
		c.EmitWithLine(vm.OpFetchStaticPropR, uint32(node.Token.Pos.Line),
			classTemp,
			propTemp,
			resultTemp)
		return nil

	// Static Method Call (Class::method())
	case *ast.StaticCallExpression:
		// Compile the class name (could be identifier or dynamic)
		if err := c.Compile(node.Class); err != nil {
			return err
		}
		classTemp := c.CurrentTemp()

		// Compile the method name (could be identifier or dynamic)
		if err := c.Compile(node.Method); err != nil {
			return err
		}
		methodTemp := c.CurrentTemp()

		// Compile arguments
		for _, arg := range node.Arguments {
			if err := c.Compile(arg.Value); err != nil {
				return err
			}
			// TODO: Push arguments onto stack properly
		}

		// Initialize static method call
		c.EmitWithLine(vm.OpInitStaticMethodCall, uint32(node.Token.Pos.Line),
			classTemp,
			methodTemp,
			vm.UnusedOperand())

		// Allocate result temp and execute method call with argument count in extended value
		resultTemp := c.AllocTemp()
		c.EmitWithExtended(vm.OpDoFcall, uint32(node.Token.Pos.Line),
			uint32(len(node.Arguments)),
			vm.UnusedOperand(),
			vm.UnusedOperand(),
			resultTemp)
		return nil

	// Isset Expression
	case *ast.IssetExpression:
		// isset() checks if variables are set and not null
		// isset($a) returns true if $a is set and not null
		// isset($a, $b, $c) returns true if ALL variables are set and not null
		//
		// IMPORTANT: isset() does NOT fetch the variable value - it checks if it exists
		// We must pass the CV index directly, not compile the variable

		if len(node.Variables) == 0 {
			// Empty isset() - shouldn't happen (parser should catch this)
			return fmt.Errorf("isset() requires at least one argument")
		}

		// Helper function to get CV operand from variable expression
		getVarOperand := func(expr ast.Expr) (vm.Operand, error) {
			if variable, ok := expr.(*ast.Variable); ok {
				// IMPORTANT: isset() should NOT define variables
				// If the variable doesn't exist, we still need to check it
				// So we define it as undefined for the check, but don't initialize it
				symbol, ok := c.ResolveVariable(variable.Name)
				if !ok {
					// Define the variable but DON'T initialize it
					// This allows isset() to check an undefined variable
					symbol = c.DefineVariable(variable.Name)
				}
				return vm.CVOperand(uint32(symbol.Index)), nil
			}
			// For more complex expressions (like $arr['key']), we'd need to compile them
			// For now, just compile and get the temp
			if err := c.Compile(expr); err != nil {
				return vm.UnusedOperand(), err
			}
			return c.CurrentTemp(), nil
		}

		// For single variable, it's simple
		if len(node.Variables) == 1 {
			varOperand, err := getVarOperand(node.Variables[0])
			if err != nil {
				return err
			}

			resultTemp := c.AllocTemp()
			c.EmitWithLine(vm.OpIssetIsemptyVar, uint32(node.Token.Pos.Line),
				varOperand,
				vm.ConstOperand(0), // 0 = isset mode (not empty mode)
				resultTemp)
			return nil
		}

		// For multiple variables, use short-circuit evaluation
		// Track jumps to the end (when a variable is not set)
		var endJumps []int

		for i, variable := range node.Variables {
			varOperand, err := getVarOperand(variable)
			if err != nil {
				return err
			}

			// Emit isset check
			resultTemp := c.AllocTemp()
			c.EmitWithLine(vm.OpIssetIsemptyVar, uint32(node.Token.Pos.Line),
				varOperand,
				vm.ConstOperand(0), // 0 = isset mode
				resultTemp)

			// If this is not the last variable, check if it's false
			// If false, jump to end
			if i < len(node.Variables)-1 {
				jmpPos := c.EmitWithLine(vm.OpJmpZ, uint32(node.Token.Pos.Line),
					resultTemp,
					vm.TmpVarOperand(0), // placeholder address
					vm.UnusedOperand())
				endJumps = append(endJumps, jmpPos)
			}
			// If we reach here and it's the last variable, result is in resultTemp
		}

		// Patch all jumps to point here (end of isset() evaluation)
		endPos := c.CurrentPosition()
		for _, jmpPos := range endJumps {
			c.PatchJump(jmpPos, 1, endPos)
		}

		return nil

	// Empty Expression
	case *ast.EmptyExpression:
		// empty() checks if a variable is empty (falsy or not set)
		// Returns true if the variable is not set or is falsy
		// Falsy values: false, 0, 0.0, "", "0", null, empty array
		//
		// IMPORTANT: empty() does NOT fetch the variable value - it checks if it exists and is falsy
		// We must pass the CV index directly for simple variables

		// Get the variable operand
		var varOperand vm.Operand
		if variable, ok := node.Variable.(*ast.Variable); ok {
			// Look up or define the variable
			symbol, ok := c.ResolveVariable(variable.Name)
			if !ok {
				symbol = c.DefineVariable(variable.Name)
			}
			varOperand = vm.CVOperand(uint32(symbol.Index))
		} else {
			// For more complex expressions (like $arr['key']), compile them
			if err := c.Compile(node.Variable); err != nil {
				return err
			}
			varOperand = c.CurrentTemp()
		}

		// Emit empty check
		resultTemp := c.AllocTemp()
		c.EmitWithLine(vm.OpIssetIsemptyVar, uint32(node.Token.Pos.Line),
			varOperand,
			vm.ConstOperand(1), // 1 = empty mode (not isset mode)
			resultTemp)

		return nil

	case *ast.IncludeExpression:
		// include, include_once, require, require_once
		// These load and execute PHP files
		//
		// Compile the path expression
		if err := c.Compile(node.Path); err != nil {
			return err
		}

		// Determine include type
		// 0 = include, 1 = include_once, 2 = require, 3 = require_once
		includeType := uint32(0)
		switch node.Type {
		case "include":
			includeType = 0
		case "include_once":
			includeType = 1
		case "require":
			includeType = 2
		case "require_once":
			includeType = 3
		}

		// Emit INCLUDE_OR_EVAL opcode
		resultTemp := c.AllocTemp()
		c.EmitWithLine(vm.OpIncludeOrEval, uint32(node.Token.Pos.Line),
			vm.TmpVarOperand(0),              // Path from previous compilation
			vm.ConstOperand(includeType),     // Include type
			resultTemp)                        // Result goes to temp

		return nil

	// Ternary Operator
	case *ast.TernaryExpression:
		// Compile the condition
		if err := c.Compile(node.Condition); err != nil {
			return err
		}

		// Short ternary form: $x ?: $y (if $x is falsy, use $y)
		if node.Consequence == nil {
			// Use JMP_SET: if (condition) { result = condition; goto end; }
			// Emit JMP_SET with placeholder address
			jmpSetPos := c.EmitWithLine(vm.OpJmpSet, uint32(node.Token.Pos.Line),
				vm.TmpVarOperand(0),
				vm.UnusedOperand(),
				vm.TmpVarOperand(1)) // Result in temp 1

			// Compile alternative (used if condition is falsy)
			if err := c.Compile(node.Alternative); err != nil {
				return err
			}
			// Move alternative to result
			c.EmitWithLine(vm.OpQMAssign, uint32(node.Token.Pos.Line),
				vm.TmpVarOperand(0),
				vm.UnusedOperand(),
				vm.TmpVarOperand(1))

			// Patch JMP_SET to jump here
			endPos := c.CurrentPosition()
			c.PatchJump(jmpSetPos, 2, endPos)
			return nil
		}

		// Full ternary form: $x ? $y : $z
		// JMPZ consequence_end with placeholder
		jmpzPos := c.EmitWithLine(vm.OpJmpZ, uint32(node.Token.Pos.Line),
			vm.TmpVarOperand(0),
			vm.UnusedOperand(),
			vm.UnusedOperand())

		// Compile consequence (true branch)
		if err := c.Compile(node.Consequence); err != nil {
			return err
		}
		// Move consequence to result
		c.EmitWithLine(vm.OpQMAssign, uint32(node.Token.Pos.Line),
			vm.TmpVarOperand(0),
			vm.UnusedOperand(),
			vm.TmpVarOperand(1)) // Result in temp 1

		// JMP to end with placeholder
		jmpEndPos := c.EmitWithLine(vm.OpJmp, uint32(node.Token.Pos.Line),
			vm.UnusedOperand(),
			vm.UnusedOperand(),
			vm.UnusedOperand())

		// Patch JMPZ to jump to alternative
		altPos := c.CurrentPosition()
		c.PatchJump(jmpzPos, 2, altPos)

		// Compile alternative (false branch)
		if err := c.Compile(node.Alternative); err != nil {
			return err
		}
		// Move alternative to result
		c.EmitWithLine(vm.OpQMAssign, uint32(node.Token.Pos.Line),
			vm.TmpVarOperand(0),
			vm.UnusedOperand(),
			vm.TmpVarOperand(1))

		// Patch JMP to jump to end
		endPos := c.CurrentPosition()
		c.PatchJump(jmpEndPos, 1, endPos)
		return nil

	// Type Cast
	case *ast.CastExpression:
		// Compile the expression to cast
		if err := c.Compile(node.Expr); err != nil {
			return err
		}

		// Map cast type to opcode extended value
		var castType uint32
		switch node.Type {
		case "int", "integer":
			castType = 1
		case "bool", "boolean":
			castType = 2
		case "float", "double", "real":
			castType = 3
		case "string":
			castType = 4
		case "array":
			castType = 5
		case "object":
			castType = 6
		case "unset":
			castType = 7
		default:
			return fmt.Errorf("unknown cast type: %s", node.Type)
		}

		// Emit CAST instruction
		c.EmitWithExtended(vm.OpCast, uint32(node.Token.Pos.Line),
			castType,
			vm.TmpVarOperand(0),
			vm.UnusedOperand(),
			vm.TmpVarOperand(1)) // Result in temp 1
		return nil

	// Instanceof
	case *ast.InstanceofExpression:
		// Compile the left side (object)
		if err := c.Compile(node.Left); err != nil {
			return err
		}
		objTemp := vm.TmpVarOperand(0)

		// Compile the right side (class name/expression)
		if err := c.Compile(node.Right); err != nil {
			return err
		}
		classTemp := vm.TmpVarOperand(1)

		// Emit INSTANCEOF instruction
		c.EmitWithLine(vm.OpInstanceof, uint32(node.Token.Pos.Line),
			objTemp,
			classTemp,
			vm.TmpVarOperand(2)) // Result in temp 2
		return nil

	// New Expression (object instantiation)
	case *ast.NewExpression:
		// Compile class name
		if err := c.Compile(node.Class); err != nil {
			return err
		}
		classTemp := vm.TmpVarOperand(0)

		// Compile constructor arguments
		for _, arg := range node.Arguments {
			if err := c.Compile(arg.Value); err != nil {
				return err
			}
			// TODO: Push arguments onto stack properly
		}

		// NEW instruction with argument count in extended value
		c.EmitWithExtended(vm.OpNew, uint32(node.Token.Pos.Line),
			uint32(len(node.Arguments)),
			classTemp,
			vm.UnusedOperand(),
			vm.TmpVarOperand(1)) // New object in temp 1
		return nil

	// ========================================
	// Control Flow Statements
	// ========================================

	// If Statement
	case *ast.IfStatement:
		// Compile condition
		if err := c.Compile(node.Condition); err != nil {
			return err
		}

		// JMPZ to alternative/end if condition is false
		jmpzPos := c.EmitWithLine(vm.OpJmpZ, uint32(node.Token.Pos.Line),
			vm.TmpVarOperand(0),
			vm.UnusedOperand(),
			vm.UnusedOperand())

		// Compile consequence block
		if err := c.Compile(node.Consequence); err != nil {
			return err
		}

		// JMP to end (skip elseif/else)
		jmpEndPos := c.EmitWithLine(vm.OpJmp, uint32(node.Token.Pos.Line),
			vm.UnusedOperand(),
			vm.UnusedOperand(),
			vm.UnusedOperand())

		// Patch JMPZ to point here
		altStart := c.CurrentPosition()
		c.PatchJump(jmpzPos, 2, altStart)

		// Track positions for elseif jumps
		elseifJumps := []int{}

		// Compile elseif clauses
		for _, elseif := range node.ElseIfs {
			// Compile elseif condition
			if err := c.Compile(elseif.Condition); err != nil {
				return err
			}

			// JMPZ to next elseif/else
			elseifJmpz := c.EmitWithLine(vm.OpJmpZ, uint32(elseif.Token.Pos.Line),
				vm.TmpVarOperand(0),
				vm.UnusedOperand(),
				vm.UnusedOperand())

			// Compile elseif consequence
			if err := c.Compile(elseif.Consequence); err != nil {
				return err
			}

			// JMP to end
			elseifJmpEnd := c.EmitWithLine(vm.OpJmp, uint32(elseif.Token.Pos.Line),
				vm.UnusedOperand(),
				vm.UnusedOperand(),
				vm.UnusedOperand())
			elseifJumps = append(elseifJumps, elseifJmpEnd)

			// Patch JMPZ to next clause
			nextClause := c.CurrentPosition()
			c.PatchJump(elseifJmpz, 2, nextClause)
		}

		// Compile alternative (else) if present
		if node.Alternative != nil {
			if err := c.Compile(node.Alternative); err != nil {
				return err
			}
		}

		// Patch all jumps to end
		endPos := c.CurrentPosition()
		c.PatchJump(jmpEndPos, 1, endPos)
		for _, jmp := range elseifJumps {
			c.PatchJump(jmp, 1, endPos)
		}
		return nil

	// While Loop
	case *ast.WhileStatement:
		// Remember start position for continue
		startPos := c.CurrentPosition()
		c.EnterLoop(startPos)

		// Compile condition
		if err := c.Compile(node.Condition); err != nil {
			return err
		}

		// JMPZ to end if condition is false
		// Condition result is in CurrentTemp() after compilation
		jmpzPos := c.EmitWithLine(vm.OpJmpZ, uint32(node.Token.Pos.Line),
			c.CurrentTemp(),
			vm.UnusedOperand(),
			vm.UnusedOperand())

		// Compile loop body
		if err := c.Compile(node.Body); err != nil {
			return err
		}

		// JMP back to start
		// Add start position to constants for backward jump
		startPosConst := c.AddConstant(int64(startPos))
		c.EmitWithLine(vm.OpJmp, uint32(node.Token.Pos.Line),
			vm.ConstOperand(uint32(startPosConst)),
			vm.UnusedOperand(),
			vm.UnusedOperand())

		// Patch JMPZ to jump here (end of loop)
		endPos := c.CurrentPosition()
		c.PatchJump(jmpzPos, 2, endPos)

		// Exit loop and patch break/continue
		c.ExitLoop(endPos)
		return nil

	// For Loop
	case *ast.ForStatement:
		// Compile initialization expressions
		for _, init := range node.Init {
			if err := c.Compile(init); err != nil {
				return err
			}
			// Free the result if there is one
			if len(c.tempVarStack) > 0 {
				c.Emit(vm.OpFree, c.CurrentTemp())
			}
		}

		// Remember condition start position
		condStart := c.CurrentPosition()
		c.EnterLoop(condStart)

		// Compile condition (if any)
		var jmpzPos int
		if len(node.Condition) > 0 {
			// Evaluate all conditions with AND logic
			for i, cond := range node.Condition {
				if err := c.Compile(cond); err != nil {
					return err
				}
				if i < len(node.Condition)-1 {
					// Not the last condition, short-circuit if false
					jmpz := c.EmitWithLine(vm.OpJmpZ, uint32(node.Token.Pos.Line),
						c.CurrentTemp(),
						vm.UnusedOperand(),
						vm.UnusedOperand())
					if i == 0 {
						jmpzPos = jmpz
					}
				}
			}
			// Final JMPZ to exit loop
			finalJmpz := c.EmitWithLine(vm.OpJmpZ, uint32(node.Token.Pos.Line),
				c.CurrentTemp(),
				vm.UnusedOperand(),
				vm.UnusedOperand())
			if len(node.Condition) == 1 {
				jmpzPos = finalJmpz
			}
		}

		// Compile loop body
		if err := c.Compile(node.Body); err != nil {
			return err
		}

		// Remember increment position for continue
		incrementPos := c.CurrentPosition()

		// Compile increment expressions
		for _, inc := range node.Increment {
			if err := c.Compile(inc); err != nil {
				return err
			}
			// Free the result if there is one
			if len(c.tempVarStack) > 0 {
				c.Emit(vm.OpFree, c.CurrentTemp())
			}
		}

		// JMP back to condition
		// Add condition start position to constants for backward jump
		condStartConst := c.AddConstant(int64(condStart))
		c.EmitWithLine(vm.OpJmp, uint32(node.Token.Pos.Line),
			vm.ConstOperand(uint32(condStartConst)),
			vm.UnusedOperand(),
			vm.UnusedOperand())

		// Patch condition JMPZ to jump here (end of loop)
		endPos := c.CurrentPosition()
		if len(node.Condition) > 0 {
			c.PatchJump(jmpzPos, 2, endPos)
		}

		// Update loop context to use increment position for continue
		if loop := c.CurrentLoop(); loop != nil {
			loop.startPos = incrementPos
		}

		// Exit loop and patch break/continue
		c.ExitLoop(endPos)
		return nil

	// Foreach Loop
	case *ast.ForeachStatement:
		// Save the current temp var stack level
		savedTempLevel := len(c.tempVarStack)

		// Compile array expression
		if err := c.Compile(node.Array); err != nil {
			return err
		}

		// The result is now in CurrentTemp()
		arrayOp := c.CurrentTemp()

		// Choose reset opcode based on by-ref
		resetOp := vm.OpFeResetR
		fetchOp := vm.OpFeFetchR
		if node.ByRef {
			resetOp = vm.OpFeResetRW
			fetchOp = vm.OpFeFetchRW
		}

		// Allocate temp for iterator
		iteratorTemp := c.AllocTemp()

		// FE_RESET: Initialize foreach iterator
		// Op1: Array value
		// Result: Iterator
		c.EmitWithLine(resetOp, uint32(node.Token.Pos.Line),
			arrayOp,
			vm.UnusedOperand(),
			iteratorTemp)

		// Allocate temps for value and key (allocated after iterator)
		valueTemp := c.AllocTemp()
		keyTemp := c.AllocTemp()

		// Remember start position for continue
		startPos := c.CurrentPosition()
		c.EnterLoop(startPos)

		// FE_FETCH: Fetch next element (jumps to end if done)
		// Op1: Iterator
		// Op2: Jump target (patched later)
		// Result: Fetched value
		// Note: The FE_FETCH handler stores the key in Result+1 (valueTemp+1 = keyTemp)
		jmpEndPos := c.EmitWithLine(fetchOp, uint32(node.Token.Pos.Line),
			iteratorTemp,
			vm.UnusedOperand(),
			valueTemp)

		// Assign key if present
		if node.Key != nil {
			if keyVar, ok := node.Key.(*ast.Variable); ok {
				symbol, ok := c.ResolveVariable(keyVar.Name)
				if !ok {
					symbol = c.DefineVariable(keyVar.Name)
				}
				// Assign key - the FE_FETCH handler stores it in keyTemp
				c.EmitWithLine(vm.OpAssign, uint32(node.Token.Pos.Line),
					keyTemp,
					vm.UnusedOperand(),
					vm.CVOperand(uint32(symbol.Index)))
			}
		}

		// Assign value
		if valueVar, ok := node.Value.(*ast.Variable); ok {
			symbol, ok := c.ResolveVariable(valueVar.Name)
			if !ok {
				symbol = c.DefineVariable(valueVar.Name)
			}
			// Assign value
			c.EmitWithLine(vm.OpAssign, uint32(node.Token.Pos.Line),
				valueTemp,
				vm.UnusedOperand(),
				vm.CVOperand(uint32(symbol.Index)))
		}

		// Compile loop body
		if err := c.Compile(node.Body); err != nil {
			return err
		}

		// JMP back to FE_FETCH
		foreachStartConst := c.AddConstant(int64(startPos))
		c.EmitWithLine(vm.OpJmp, uint32(node.Token.Pos.Line),
			vm.ConstOperand(uint32(foreachStartConst)),
			vm.UnusedOperand(),
			vm.UnusedOperand())

		// End position
		endPos := c.CurrentPosition()

		// Patch FE_FETCH jump (operand 2 is Op2, the jump target)
		c.PatchJump(jmpEndPos, 2, endPos)

		// FE_FREE: Clean up iterator
		c.EmitWithLine(vm.OpFeFree, uint32(node.Token.Pos.Line),
			iteratorTemp,
			vm.UnusedOperand(),
			vm.UnusedOperand())

		// Restore temp stack to saved level
		c.tempVarStack = c.tempVarStack[:savedTempLevel]

		// Exit loop and patch break/continue
		c.ExitLoop(endPos)
		return nil

	// Break Statement
	case *ast.BreakStatement:
		if !c.InLoop() {
			return fmt.Errorf("break statement outside of loop")
		}

		// Emit JMP with placeholder (will be patched by ExitLoop)
		jmpPos := c.EmitWithLine(vm.OpJmp, uint32(node.Token.Pos.Line),
			vm.UnusedOperand(),
			vm.UnusedOperand(),
			vm.UnusedOperand())

		// Add to current loop's break jumps
		loop := c.CurrentLoop()
		loop.breakJumps = append(loop.breakJumps, jmpPos)
		return nil

	// Continue Statement
	case *ast.ContinueStatement:
		if !c.InLoop() {
			return fmt.Errorf("continue statement outside of loop")
		}

		// Emit JMP with placeholder (will be patched by ExitLoop)
		jmpPos := c.EmitWithLine(vm.OpJmp, uint32(node.Token.Pos.Line),
			vm.UnusedOperand(),
			vm.UnusedOperand(),
			vm.UnusedOperand())

		// Add to current loop's continue jumps
		loop := c.CurrentLoop()
		loop.continueJumps = append(loop.continueJumps, jmpPos)
		return nil

	// Switch Statement
	case *ast.SwitchStatement:
		// Compile switch subject
		if err := c.Compile(node.Subject); err != nil {
			return err
		}
		subjectTemp := vm.TmpVarOperand(0)

		// Track case jump positions
		caseJumps := []int{}
		var defaultCase *ast.SwitchCase

		// Enter switch as a loop context (for break)
		c.EnterLoop(c.CurrentPosition())

		// Compile each case
		for _, switchCase := range node.Cases {
			if switchCase.Value == nil {
				// Default case
				defaultCase = switchCase
				continue
			}

			// Compile case value
			if err := c.Compile(switchCase.Value); err != nil {
				return err
			}
			caseValueTemp := vm.TmpVarOperand(1)

			// Compare subject == case value
			c.EmitWithLine(vm.OpIsEqual, uint32(switchCase.Token.Pos.Line),
				subjectTemp,
				caseValueTemp,
				vm.TmpVarOperand(2)) // Result in temp 2

			// JMPNZ to case body if equal
			jmpCase := c.EmitWithLine(vm.OpJmpNZ, uint32(switchCase.Token.Pos.Line),
				vm.TmpVarOperand(2),
				vm.UnusedOperand(),
				vm.UnusedOperand())
			caseJumps = append(caseJumps, jmpCase)
		}

		// If no match, jump to default or end
		jmpDefault := c.EmitWithLine(vm.OpJmp, uint32(node.Token.Pos.Line),
			vm.UnusedOperand(),
			vm.UnusedOperand(),
			vm.UnusedOperand())

		// Compile case bodies
		for i, switchCase := range node.Cases {
			if switchCase.Value == nil {
				continue // Skip default, compile it later
			}

			// Patch jump to this case
			caseBodyPos := c.CurrentPosition()
			c.PatchJump(caseJumps[i], 1, caseBodyPos)

			// Compile case statements
			for _, stmt := range switchCase.Body {
				if err := c.Compile(stmt); err != nil {
					return err
				}
			}
			// Note: PHP switch has fall-through by default, no automatic jump to end
		}

		// Compile default case if present
		if defaultCase != nil {
			defaultBodyPos := c.CurrentPosition()
			c.PatchJump(jmpDefault, 1, defaultBodyPos)

			for _, stmt := range defaultCase.Body {
				if err := c.Compile(stmt); err != nil {
					return err
				}
			}
		} else {
			// No default case, patch jump to end
			endPos := c.CurrentPosition()
			c.PatchJump(jmpDefault, 1, endPos)
		}

		// End of switch
		endPos := c.CurrentPosition()
		c.ExitLoop(endPos)
		return nil

	// Try-Catch-Finally Statement
	case *ast.TryStatement:
		// For now, implement simplified version
		// Full exception handling requires VM support

		// Use FAST_CALL for finally block if present
		var fastCallPos int
		if node.Finally != nil {
			fastCallPos = c.EmitWithLine(vm.OpFastCall, uint32(node.Token.Pos.Line),
				vm.UnusedOperand(),
				vm.UnusedOperand(),
				vm.UnusedOperand())
		}

		// Compile try block
		if err := c.Compile(node.Body); err != nil {
			return err
		}

		// JMP over catch blocks
		jmpEndPos := c.EmitWithLine(vm.OpJmp, uint32(node.Token.Pos.Line),
			vm.UnusedOperand(),
			vm.UnusedOperand(),
			vm.UnusedOperand())

		// Compile catch clauses
		for _, catchClause := range node.CatchClauses {
			// CATCH opcode
			c.EmitWithLine(vm.OpCatch, uint32(catchClause.Token.Pos.Line),
				vm.UnusedOperand(),
				vm.UnusedOperand(),
				vm.TmpVarOperand(0)) // Exception in temp 0

			// Assign exception to variable
			if catchClause.Variable != nil {
				symbol, ok := c.ResolveVariable(catchClause.Variable.Name)
				if !ok {
					symbol = c.DefineVariable(catchClause.Variable.Name)
				}
				c.EmitWithLine(vm.OpAssign, uint32(catchClause.Token.Pos.Line),
					vm.TmpVarOperand(0),
					vm.UnusedOperand(),
					vm.CVOperand(uint32(symbol.Index)))
			}

			// Compile catch block
			if err := c.Compile(catchClause.Body); err != nil {
				return err
			}

			// JMP to finally/end
			c.EmitWithLine(vm.OpJmp, uint32(catchClause.Token.Pos.Line),
				vm.UnusedOperand(),
				vm.UnusedOperand(),
				vm.UnusedOperand())
		}

		// End position
		endPos := c.CurrentPosition()
		c.PatchJump(jmpEndPos, 1, endPos)

		// Compile finally block if present
		if node.Finally != nil {
			finallyPos := c.CurrentPosition()
			c.PatchJump(fastCallPos, 1, finallyPos)

			if err := c.Compile(node.Finally); err != nil {
				return err
			}

			// FAST_RET to return from finally
			c.EmitWithLine(vm.OpFastRet, uint32(node.Token.Pos.Line),
				vm.UnusedOperand(),
				vm.UnusedOperand(),
				vm.UnusedOperand())
		}
		return nil

	// Throw Statement
	case *ast.ThrowStatement:
		// Compile exception expression
		if err := c.Compile(node.Expression); err != nil {
			return err
		}

		// THROW instruction
		c.EmitWithLine(vm.OpThrow, uint32(node.Token.Pos.Line),
			vm.TmpVarOperand(0),
			vm.UnusedOperand(),
			vm.UnusedOperand())
		return nil

	// ========================================
	// Function and Class Declarations
	// ========================================

	// Function Declaration
	case *ast.FunctionDeclaration:
		// Store function name as constant
		funcNameIdx := c.AddConstant(node.Name.Value)

		// DECLARE_FUNCTION will be emitted here with placeholders
		// We need to know funcStart and funcEnd first, so we'll do a two-pass approach:
		// 1. Mark where DECLARE_FUNCTION will go
		// 2. Compile function body
		// 3. Patch DECLARE_FUNCTION with actual positions

		// Emit placeholder DECLARE_FUNCTION (will be patched)
		declareFuncPos := c.EmitWithExtended(vm.OpDeclareFunction, uint32(node.Token.Pos.Line),
			uint32(len(node.Parameters)),         // Number of parameters
			vm.ConstOperand(uint32(funcNameIdx)), // Function name
			vm.UnusedOperand(),                   // Function start position (will be patched)
			vm.UnusedOperand())                   // Function end position (will be patched)

		// Emit JMP to skip over function body (will be patched later)
		jmpPos := c.EmitWithLine(vm.OpJmp, uint32(node.Token.Pos.Line),
			vm.UnusedOperand(), // Will be patched with jump target (Op1)
			vm.UnusedOperand(),
			vm.UnusedOperand())

		// Remember function start position (after the DECLARE_FUNCTION and JMP)
		funcStart := c.CurrentPosition()

		// Enter new scope for function
		c.EnterScope()

		// Emit RECV opcodes for each parameter
		for i, param := range node.Parameters {
			// Define parameter variable in function scope
			symbol := c.DefineVariable(param.Name.Name)

			// Add parameter index to constants
			paramIdxConst := c.AddConstant(int64(i))

			if param.Variadic {
				// RECV_VARIADIC for ...args
				c.EmitWithLine(vm.OpRecvVariadic, uint32(node.Token.Pos.Line),
					vm.ConstOperand(uint32(paramIdxConst)), // Parameter index from constants
					vm.UnusedOperand(),
					vm.CVOperand(uint32(symbol.Index))) // Store in compiled variable
			} else if param.DefaultValue != nil {
				// RECV_INIT for parameters with defaults
				// Compile default value
				if err := c.Compile(param.DefaultValue); err != nil {
					return err
				}

				c.EmitWithLine(vm.OpRecvInit, uint32(node.Token.Pos.Line),
					vm.ConstOperand(uint32(paramIdxConst)), // Parameter index from constants
					vm.TmpVarOperand(0),                    // Default value in temp 0
					vm.CVOperand(uint32(symbol.Index)))     // Store in compiled variable
			} else {
				// RECV for required parameters
				recvOp := vm.OpRecv
				if param.ByRef {
					recvOp = vm.OpSendRef // Use SEND_REF for by-reference parameters
				}

				c.EmitWithLine(recvOp, uint32(node.Token.Pos.Line),
					vm.ConstOperand(uint32(paramIdxConst)), // Parameter index from constants
					vm.UnusedOperand(),
					vm.CVOperand(uint32(symbol.Index))) // Store in compiled variable
			}
		}

		// Compile function body
		if err := c.Compile(node.Body); err != nil {
			return err
		}

		// Add implicit return if function doesn't end with return
		if !c.LastInstructionIs(vm.OpReturn) && !c.LastInstructionIs(vm.OpReturnByRef) {
			// Return null
			c.EmitWithLine(vm.OpReturn, uint32(node.Token.Pos.Line),
				vm.UnusedOperand(),
				vm.UnusedOperand(),
				vm.UnusedOperand())
		}

		// Exit function scope
		c.ExitScope()

		// Function end position
		funcEnd := c.CurrentPosition()

		// Patch the DECLARE_FUNCTION with actual function positions
		// Op2 = funcStart, Result = funcEnd
		c.PatchJump(declareFuncPos, 2, funcStart)
		c.PatchJump(declareFuncPos, 3, funcEnd)

		// Patch the JMP to skip over the function body
		afterFunc := c.CurrentPosition()
		c.PatchJump(jmpPos, 1, afterFunc)

		return nil

	// Class Declaration
	case *ast.ClassDeclaration:
		// Store class name as constant
		classNameIdx := c.AddConstant(node.Name.Value)

		// Store parent class name if extends
		var parentIdx int
		if node.Extends != nil {
			parentIdx = c.AddConstant(node.Extends.Value)
		}

		// Remember class body start position
		classStart := c.CurrentPosition()

		// Compile class body (properties and methods)
		for _, stmt := range node.Body {
			switch decl := stmt.(type) {
			case *ast.PropertyDeclaration:
				// Compile property declarations
				// Instance properties are initialized when the class is instantiated
				// Static properties are initialized at class declaration time
				for _, prop := range decl.Properties {
					// Store property name as constant
					propNameIdx := c.AddConstant(prop.Name.Name)

					if decl.Static {
						// Static property: initialize immediately
						if prop.DefaultValue != nil {
							// Compile default value
							if err := c.Compile(prop.DefaultValue); err != nil {
								return err
							}

							// ASSIGN_STATIC_PROP to initialize the static property
							c.EmitWithLine(vm.OpAssignStaticProp, uint32(node.Token.Pos.Line),
								vm.ConstOperand(uint32(classNameIdx)), // Class name
								vm.ConstOperand(uint32(propNameIdx)),  // Property name
								vm.TmpVarOperand(0))                   // Value in temp var 0
						}
						// If no default value, static property remains uninitialized (null)
					} else {
						// Instance property: just note existence
						// Will be initialized when the class is instantiated
						if prop.DefaultValue != nil {
							if err := c.Compile(prop.DefaultValue); err != nil {
								return err
							}
						}
					}
				}

			case *ast.MethodDeclaration:
				// Compile method similar to function but in class context
				methodNameIdx := c.AddConstant(decl.Name.Value)

				// Skip abstract methods (no body)
				if decl.Abstract || decl.Body == nil {
					continue
				}

				methodStart := c.CurrentPosition()

				// Enter new scope for method
				c.EnterScope()

				// Instance methods have implicit $this parameter
				// Static methods do NOT have $this
				if !decl.Static {
					c.DefineVariable("this")
				}

				// Emit RECV opcodes for each parameter
				for i, param := range decl.Parameters {
					symbol := c.DefineVariable(param.Name.Name)

					// Add parameter index to constants pool
					paramIdxConst := c.AddConstant(int64(i))

					if param.Variadic {
						c.EmitWithLine(vm.OpRecvVariadic, uint32(decl.Token.Pos.Line),
							vm.ConstOperand(uint32(paramIdxConst)),
							vm.UnusedOperand(),
							vm.CVOperand(uint32(symbol.Index)))
					} else if param.DefaultValue != nil {
						if err := c.Compile(param.DefaultValue); err != nil {
							return err
						}
						c.EmitWithLine(vm.OpRecvInit, uint32(decl.Token.Pos.Line),
							vm.ConstOperand(uint32(paramIdxConst)),
							vm.TmpVarOperand(0),
							vm.CVOperand(uint32(symbol.Index)))
					} else {
						recvOp := vm.OpRecv
						if param.ByRef {
							recvOp = vm.OpSendRef
						}
						c.EmitWithLine(recvOp, uint32(decl.Token.Pos.Line),
							vm.ConstOperand(uint32(paramIdxConst)),
							vm.UnusedOperand(),
							vm.CVOperand(uint32(symbol.Index)))
					}
				}

				// Compile method body
				if err := c.Compile(decl.Body); err != nil {
					return err
				}

				// Add implicit return if method doesn't end with return
				if !c.LastInstructionIs(vm.OpReturn) && !c.LastInstructionIs(vm.OpReturnByRef) {
					c.EmitWithLine(vm.OpReturn, uint32(decl.Token.Pos.Line),
						vm.UnusedOperand(),
						vm.UnusedOperand(),
						vm.UnusedOperand())
				}

				// Exit method scope
				c.ExitScope()

				methodEnd := c.CurrentPosition()

				// Store method metadata
				_ = methodNameIdx
				_ = methodStart
				_ = methodEnd

			default:
				// Other class body elements (constants, trait uses, etc.)
				if err := c.Compile(stmt); err != nil {
					return err
				}
			}
		}

		// Class end position
		classEnd := c.CurrentPosition()

		// DECLARE_CLASS to register the class
		if node.Extends != nil {
			// Class with parent - use extended value for parent index
			c.EmitWithExtended(vm.OpDeclareClass, uint32(node.Token.Pos.Line),
				uint32(parentIdx),                     // Parent class name index
				vm.ConstOperand(uint32(classNameIdx)), // Class name
				vm.ConstOperand(uint32(classStart)),   // Class start position
				vm.ConstOperand(uint32(classEnd)))     // Class end position
		} else {
			// Class without parent
			c.EmitWithExtended(vm.OpDeclareClass, uint32(node.Token.Pos.Line),
				0,                                     // No parent
				vm.ConstOperand(uint32(classNameIdx)), // Class name
				vm.ConstOperand(uint32(classStart)),   // Class start position
				vm.ConstOperand(uint32(classEnd)))     // Class end position
		}

		return nil

	// Interface Declaration
	case *ast.InterfaceDeclaration:
		// Store interface name as constant
		interfaceNameIdx := c.AddConstant(node.Name.Value)

		// Store parent interface names if extends
		parentIndices := []int{}
		for _, parent := range node.Extends {
			parentIdx := c.AddConstant(parent.Value)
			parentIndices = append(parentIndices, parentIdx)
		}

		// For now, interfaces are compile-time metadata
		// We'll just note their existence
		// TODO: Implement runtime interface checking and type validation

		// Store method signatures for interface validation
		for _, methodSig := range node.Body {
			_ = methodSig // Store method signature metadata
			methodNameIdx := c.AddConstant(methodSig.Name.Value)
			_ = methodNameIdx
		}

		// Placeholder - interfaces don't generate runtime code
		// They're used for compile-time type checking
		_ = interfaceNameIdx
		_ = parentIndices

		return nil

	// Trait Declaration
	case *ast.TraitDeclaration:
		// Store trait name as constant
		traitNameIdx := c.AddConstant(node.Name.Value)

		// Traits are similar to classes but cannot be instantiated
		// They provide methods that can be included in classes

		// Remember trait body start position
		traitStart := c.CurrentPosition()

		// Compile trait body (properties and methods)
		for _, stmt := range node.Body {
			switch decl := stmt.(type) {
			case *ast.PropertyDeclaration:
				// Trait properties
				for _, prop := range decl.Properties {
					propNameIdx := c.AddConstant(prop.Name.Name)
					_ = propNameIdx

					if prop.DefaultValue != nil {
						if err := c.Compile(prop.DefaultValue); err != nil {
							return err
						}
					}
				}

			case *ast.MethodDeclaration:
				// Trait methods - compile similar to class methods
				methodNameIdx := c.AddConstant(decl.Name.Value)

				if decl.Abstract || decl.Body == nil {
					continue
				}

				methodStart := c.CurrentPosition()

				c.EnterScope()

				// Trait methods can access $this when used in a class
				if !decl.Static {
					c.DefineVariable("this")
				}

				// Emit RECV opcodes for parameters
				for i, param := range decl.Parameters {
					symbol := c.DefineVariable(param.Name.Name)

					if param.Variadic {
						c.EmitWithLine(vm.OpRecvVariadic, uint32(decl.Token.Pos.Line),
							vm.ConstOperand(uint32(i)),
							vm.UnusedOperand(),
							vm.CVOperand(uint32(symbol.Index)))
					} else if param.DefaultValue != nil {
						if err := c.Compile(param.DefaultValue); err != nil {
							return err
						}
						c.EmitWithLine(vm.OpRecvInit, uint32(decl.Token.Pos.Line),
							vm.ConstOperand(uint32(i)),
							vm.TmpVarOperand(0),
							vm.CVOperand(uint32(symbol.Index)))
					} else {
						recvOp := vm.OpRecv
						if param.ByRef {
							recvOp = vm.OpSendRef
						}
						c.EmitWithLine(recvOp, uint32(decl.Token.Pos.Line),
							vm.ConstOperand(uint32(i)),
							vm.UnusedOperand(),
							vm.CVOperand(uint32(symbol.Index)))
					}
				}

				// Compile method body
				if err := c.Compile(decl.Body); err != nil {
					return err
				}

				// Add implicit return if method doesn't end with return
				if !c.LastInstructionIs(vm.OpReturn) && !c.LastInstructionIs(vm.OpReturnByRef) {
					c.EmitWithLine(vm.OpReturn, uint32(decl.Token.Pos.Line),
						vm.UnusedOperand(),
						vm.UnusedOperand(),
						vm.UnusedOperand())
				}

				c.ExitScope()

				methodEnd := c.CurrentPosition()

				_ = methodNameIdx
				_ = methodStart
				_ = methodEnd

			default:
				if err := c.Compile(stmt); err != nil {
					return err
				}
			}
		}

		traitEnd := c.CurrentPosition()

		// TODO: Implement DECLARE_TRAIT opcode for runtime trait registration
		// For now, traits are compile-time metadata
		_ = traitNameIdx
		_ = traitStart
		_ = traitEnd

		return nil

	// Method Declaration (when standalone, though usually part of class)
	case *ast.MethodDeclaration:
		// Methods are typically compiled as part of ClassDeclaration
		// If encountered standalone, treat like a function
		return fmt.Errorf("standalone method declaration not supported")

	// Property Declaration (when standalone, though usually part of class)
	case *ast.PropertyDeclaration:
		// Properties are typically compiled as part of ClassDeclaration
		// If encountered standalone, it's likely a parse error context
		return fmt.Errorf("standalone property declaration not supported")

	default:
		return fmt.Errorf("compilation not yet implemented for node type: %T", node)
	}
}

// ========================================
// Helper Methods
// ========================================

// PatchJump patches a jump instruction with a target position
// It adds the target position to the constants pool and updates the operand
func (c *Compiler) PatchJump(instrPos int, operandNum int, targetPos int) {
	// Add target position as a constant
	targetIdx := c.AddConstant(int64(targetPos))
	// Patch the operand with the constant index
	c.ChangeOperand(instrPos, operandNum, vm.ConstOperand(uint32(targetIdx)))
}

// Instructions returns the current instruction list
func (c *Compiler) Instructions() vm.Instructions {
	return c.instructions
}

// Reset resets the compiler state for a new compilation
func (c *Compiler) Reset() {
	c.instructions = vm.Instructions{}
	c.constants = []interface{}{}
	c.constantMap = make(map[interface{}]int)
	c.lastInstruction = EmittedInstruction{}
	c.previousInstruction = EmittedInstruction{}
	c.loopStack = []*LoopContext{}
	c.InitSymbolTable()
}

// ========================================
// Loop Context Management
// ========================================

// EnterLoop pushes a new loop context onto the stack
func (c *Compiler) EnterLoop(startPos int) {
	c.loopStack = append(c.loopStack, &LoopContext{
		startPos:      startPos,
		breakJumps:    []int{},
		continueJumps: []int{},
	})
}

// ExitLoop pops a loop context and patches all break/continue jumps
func (c *Compiler) ExitLoop(endPos int) {
	if len(c.loopStack) == 0 {
		return
	}

	loop := c.loopStack[len(c.loopStack)-1]
	c.loopStack = c.loopStack[:len(c.loopStack)-1]

	// Patch all break jumps to jump to end
	for _, pos := range loop.breakJumps {
		c.PatchJump(pos, 1, endPos)
	}

	// Patch all continue jumps to jump to start
	for _, pos := range loop.continueJumps {
		c.PatchJump(pos, 1, loop.startPos)
	}
}

// CurrentLoop returns the current loop context (nil if not in a loop)
func (c *Compiler) CurrentLoop() *LoopContext {
	if len(c.loopStack) == 0 {
		return nil
	}
	return c.loopStack[len(c.loopStack)-1]
}

// InLoop returns true if currently inside a loop
func (c *Compiler) InLoop() bool {
	return len(c.loopStack) > 0
}

// ========================================
// Optimization Helpers
// ========================================

// isConstantLiteral checks if an expression is a constant literal value
func isConstantLiteral(expr ast.Expr) bool {
	switch expr.(type) {
	case *ast.IntegerLiteral, *ast.FloatLiteral, *ast.StringLiteral, *ast.BooleanLiteral, *ast.NullLiteral:
		return true
	default:
		return false
	}
}

// getConstantValue extracts the constant value from a literal expression
func getConstantValue(expr ast.Expr) (interface{}, bool) {
	switch node := expr.(type) {
	case *ast.IntegerLiteral:
		return node.Value, true
	case *ast.FloatLiteral:
		return node.Value, true
	case *ast.StringLiteral:
		return node.Value, true
	case *ast.BooleanLiteral:
		return node.Value, true
	case *ast.NullLiteral:
		return nil, true
	default:
		return nil, false
	}
}

// foldConstantBinaryOp performs constant folding for binary operations
// Returns (result value, success boolean)
func foldConstantBinaryOp(left, right interface{}, operator string) (interface{}, bool) {
	// Arithmetic operations on integers
	leftInt, leftIsInt := left.(int64)
	rightInt, rightIsInt := right.(int64)
	if leftIsInt && rightIsInt {
		switch operator {
		case "+":
			return leftInt + rightInt, true
		case "-":
			return leftInt - rightInt, true
		case "*":
			return leftInt * rightInt, true
		case "/":
			if rightInt == 0 {
				return nil, false // Don't fold division by zero
			}
			return leftInt / rightInt, true
		case "%":
			if rightInt == 0 {
				return nil, false // Don't fold modulo by zero
			}
			return leftInt % rightInt, true
		case "**":
			// Simple power for small exponents
			if rightInt >= 0 && rightInt < 100 {
				result := int64(1)
				for i := int64(0); i < rightInt; i++ {
					result *= leftInt
				}
				return result, true
			}
			return nil, false
		case "==":
			return leftInt == rightInt, true
		case "!=":
			return leftInt != rightInt, true
		case "===":
			return leftInt == rightInt, true
		case "!==":
			return leftInt != rightInt, true
		case "<":
			return leftInt < rightInt, true
		case "<=":
			return leftInt <= rightInt, true
		case ">":
			return leftInt > rightInt, true
		case ">=":
			return leftInt >= rightInt, true
		case "|":
			return leftInt | rightInt, true
		case "&":
			return leftInt & rightInt, true
		case "^":
			return leftInt ^ rightInt, true
		case "<<":
			return leftInt << uint(rightInt), true
		case ">>":
			return leftInt >> uint(rightInt), true
		case "<=>":
			if leftInt < rightInt {
				return int64(-1), true
			} else if leftInt > rightInt {
				return int64(1), true
			}
			return int64(0), true
		}
	}

	// Arithmetic operations on floats (or mixed int/float)
	var leftFloat, rightFloat float64
	var hasFloat bool
	if leftIsInt {
		leftFloat = float64(leftInt)
		hasFloat = true
	} else if f, ok := left.(float64); ok {
		leftFloat = f
		hasFloat = true
	}
	if rightIsInt {
		rightFloat = float64(rightInt)
		hasFloat = true
	} else if f, ok := right.(float64); ok {
		rightFloat = f
		hasFloat = true
	}

	if hasFloat && (leftIsInt || rightIsInt || left != nil && right != nil) {
		switch operator {
		case "+":
			return leftFloat + rightFloat, true
		case "-":
			return leftFloat - rightFloat, true
		case "*":
			return leftFloat * rightFloat, true
		case "/":
			if rightFloat == 0.0 {
				return nil, false
			}
			return leftFloat / rightFloat, true
		case "<":
			return leftFloat < rightFloat, true
		case "<=":
			return leftFloat <= rightFloat, true
		case ">":
			return leftFloat > rightFloat, true
		case ">=":
			return leftFloat >= rightFloat, true
		case "==":
			return leftFloat == rightFloat, true
		case "!=":
			return leftFloat != rightFloat, true
		}
	}

	// String concatenation
	leftStr, leftIsStr := left.(string)
	rightStr, rightIsStr := right.(string)
	if leftIsStr && rightIsStr && operator == "." {
		return leftStr + rightStr, true
	}

	// Boolean operations
	leftBool, leftIsBool := left.(bool)
	rightBool, rightIsBool := right.(bool)
	if leftIsBool && rightIsBool {
		switch operator {
		case "==":
			return leftBool == rightBool, true
		case "!=":
			return leftBool != rightBool, true
		case "===":
			return leftBool == rightBool, true
		case "!==":
			return leftBool != rightBool, true
		}
	}

	return nil, false
}

// foldConstantUnaryOp performs constant folding for unary operations
// Returns (result value, success boolean)
func foldConstantUnaryOp(operand interface{}, operator string) (interface{}, bool) {
	switch operator {
	case "!":
		// Boolean not
		if b, ok := operand.(bool); ok {
			return !b, true
		}
		// PHP truthiness for other types
		if operand == nil {
			return true, true // !null = true
		}
		if i, ok := operand.(int64); ok {
			return i == 0, true // !0 = true, !nonzero = false
		}
		if s, ok := operand.(string); ok {
			return s == "" || s == "0", true // !"" = true, !"0" = true
		}

	case "-":
		// Unary minus
		if i, ok := operand.(int64); ok {
			return -i, true
		}
		if f, ok := operand.(float64); ok {
			return -f, true
		}

	case "~":
		// Bitwise not
		if i, ok := operand.(int64); ok {
			return ^i, true
		}
	}

	return nil, false
}

// ============================================================================
// Strength Reduction Optimization
// ============================================================================

// applyStrengthReduction applies strength reduction optimizations
// Replaces expensive operations with cheaper equivalents
// Returns (optimized bool, error)
func (c *Compiler) applyStrengthReduction(node *ast.InfixExpression) (bool, error) {
	// Check for multiplication by 0: x * 0 = 0
	if node.Operator == "*" {
		if isConstantZero(node.Right) {
			// Result is always 0
			constIdx := c.AddConstant(int64(0))
			c.EmitWithLine(vm.OpQMAssign, uint32(node.Token.Pos.Line),
				vm.ConstOperand(uint32(constIdx)),
				vm.UnusedOperand(),
				vm.TmpVarOperand(0))
			return true, nil
		}
		if isConstantZero(node.Left) {
			// 0 * x = 0
			constIdx := c.AddConstant(int64(0))
			c.EmitWithLine(vm.OpQMAssign, uint32(node.Token.Pos.Line),
				vm.ConstOperand(uint32(constIdx)),
				vm.UnusedOperand(),
				vm.TmpVarOperand(0))
			return true, nil
		}
	}

	// Check for multiplication by 1: x * 1 = x
	if node.Operator == "*" && isConstantOne(node.Right) {
		// Just compile the left operand
		return true, c.Compile(node.Left)
	}
	if node.Operator == "*" && isConstantOne(node.Left) {
		// 1 * x = x
		return true, c.Compile(node.Right)
	}

	// Check for addition/subtraction by 0: x + 0 = x, x - 0 = x
	if (node.Operator == "+" || node.Operator == "-") && isConstantZero(node.Right) {
		// x + 0 = x, x - 0 = x
		return true, c.Compile(node.Left)
	}
	if node.Operator == "+" && isConstantZero(node.Left) {
		// 0 + x = x
		return true, c.Compile(node.Right)
	}

	// Check for multiplication by power of 2 (can use bit shift)
	// x * 2 → x << 1, x * 4 → x << 2, etc.
	if node.Operator == "*" {
		if powerOf2, shiftAmount := isPowerOfTwo(node.Right); powerOf2 {
			// Compile left operand
			if err := c.Compile(node.Left); err != nil {
				return true, err
			}

			// Create constant for shift amount
			shiftIdx := c.AddConstant(int64(shiftAmount))

			// Emit shift left instead of multiply
			c.EmitWithLine(vm.OpSL, uint32(node.Token.Pos.Line),
				vm.TmpVarOperand(0),               // Value to shift
				vm.ConstOperand(uint32(shiftIdx)), // Shift amount
				vm.TmpVarOperand(0))               // Result
			return true, nil
		}
		if powerOf2, shiftAmount := isPowerOfTwo(node.Left); powerOf2 {
			// 2 * x → x << 1
			if err := c.Compile(node.Right); err != nil {
				return true, err
			}

			shiftIdx := c.AddConstant(int64(shiftAmount))
			c.EmitWithLine(vm.OpSL, uint32(node.Token.Pos.Line),
				vm.TmpVarOperand(0),
				vm.ConstOperand(uint32(shiftIdx)),
				vm.TmpVarOperand(0))
			return true, nil
		}
	}

	// Check for division by power of 2 (can use bit shift)
	// x / 2 → x >> 1, x / 4 → x >> 2, etc.
	if node.Operator == "/" {
		if powerOf2, shiftAmount := isPowerOfTwo(node.Right); powerOf2 {
			// Compile left operand
			if err := c.Compile(node.Left); err != nil {
				return true, err
			}

			// Create constant for shift amount
			shiftIdx := c.AddConstant(int64(shiftAmount))

			// Emit shift right instead of divide
			c.EmitWithLine(vm.OpSR, uint32(node.Token.Pos.Line),
				vm.TmpVarOperand(0),
				vm.ConstOperand(uint32(shiftIdx)),
				vm.TmpVarOperand(0))
			return true, nil
		}
	}

	// No optimization applied
	return false, nil
}

// isConstantZero checks if an expression is the constant 0
func isConstantZero(expr ast.Expr) bool {
	if val, ok := getConstantValue(expr); ok {
		switch v := val.(type) {
		case int64:
			return v == 0
		case float64:
			return v == 0.0
		}
	}
	return false
}

// isConstantOne checks if an expression is the constant 1
func isConstantOne(expr ast.Expr) bool {
	if val, ok := getConstantValue(expr); ok {
		switch v := val.(type) {
		case int64:
			return v == 1
		case float64:
			return v == 1.0
		}
	}
	return false
}

// isPowerOfTwo checks if an expression is a constant power of 2
// Returns (isPowerOf2 bool, shiftAmount int)
func isPowerOfTwo(expr ast.Expr) (bool, int) {
	if val, ok := getConstantValue(expr); ok {
		if i, ok := val.(int64); ok && i > 0 {
			// Check if it's a power of 2 using bit manipulation
			// A number is a power of 2 if it has only one bit set
			if (i & (i - 1)) == 0 {
				// Calculate shift amount (log2)
				shiftAmount := 0
				for n := i; n > 1; n >>= 1 {
					shiftAmount++
				}
				return true, shiftAmount
			}
		}
	}
	return false, 0
}

// findReferencedVariables recursively finds all variable names referenced in an expression
// This is used for automatic variable capture in arrow functions
func findReferencedVariables(expr ast.Expr) []string {
	vars := make(map[string]bool) // Use map to avoid duplicates
	findVarsRecursive(expr, vars)

	// Convert map to slice
	result := make([]string, 0, len(vars))
	for name := range vars {
		result = append(result, name)
	}
	return result
}

// findVarsRecursive is the recursive helper for findReferencedVariables
func findVarsRecursive(node ast.Node, vars map[string]bool) {
	if node == nil {
		return
	}

	switch n := node.(type) {
	case *ast.Variable:
		// Found a variable reference
		vars[n.Name] = true

	case *ast.InfixExpression:
		findVarsRecursive(n.Left, vars)
		findVarsRecursive(n.Right, vars)

	case *ast.PrefixExpression:
		findVarsRecursive(n.Right, vars)

	case *ast.GroupedExpression:
		findVarsRecursive(n.Expr, vars)

	case *ast.TernaryExpression:
		findVarsRecursive(n.Condition, vars)
		if n.Consequence != nil {
			findVarsRecursive(n.Consequence, vars)
		}
		findVarsRecursive(n.Alternative, vars)

	case *ast.CallExpression:
		// Check function name if it's a variable
		findVarsRecursive(n.Function, vars)
		// Check arguments
		for _, arg := range n.Arguments {
			findVarsRecursive(arg.Value, vars)
		}

	case *ast.MethodCallExpression:
		findVarsRecursive(n.Object, vars)
		for _, arg := range n.Arguments {
			findVarsRecursive(arg.Value, vars)
		}

	case *ast.StaticCallExpression:
		findVarsRecursive(n.Class, vars)
		for _, arg := range n.Arguments {
			findVarsRecursive(arg.Value, vars)
		}

	case *ast.PropertyExpression:
		findVarsRecursive(n.Object, vars)
		findVarsRecursive(n.Property, vars)

	case *ast.NullsafePropertyExpression:
		findVarsRecursive(n.Object, vars)
		findVarsRecursive(n.Property, vars)

	case *ast.StaticPropertyExpression:
		findVarsRecursive(n.Class, vars)
		findVarsRecursive(n.Property, vars)

	case *ast.ArrayExpression:
		for _, elem := range n.Elements {
			if elem.Key != nil {
				findVarsRecursive(elem.Key, vars)
			}
			findVarsRecursive(elem.Value, vars)
		}

	case *ast.IndexExpression:
		findVarsRecursive(n.Left, vars)
		findVarsRecursive(n.Index, vars)

	case *ast.AssignmentExpression:
		findVarsRecursive(n.Left, vars)
		findVarsRecursive(n.Right, vars)

	case *ast.ClosureExpression:
		// Don't traverse into closure body - it has its own scope
		// But do check use clause variables
		for _, use := range n.Use {
			vars[use.Variable.Name] = true
		}

	case *ast.ArrowFunctionExpression:
		// Don't traverse into arrow function body - it has its own scope
		// Arrow functions auto-capture, so we don't need to track their references

	case *ast.NewExpression:
		// Check arguments
		for _, arg := range n.Arguments {
			findVarsRecursive(arg.Value, vars)
		}

	case *ast.CastExpression:
		findVarsRecursive(n.Expr, vars)

	case *ast.InstanceofExpression:
		findVarsRecursive(n.Left, vars)
		findVarsRecursive(n.Right, vars)

	// Literal values don't reference variables
	case *ast.IntegerLiteral, *ast.FloatLiteral, *ast.StringLiteral,
		*ast.BooleanLiteral, *ast.NullLiteral:
		// No variables in literals

		// Default: ignore unknown node types
	}
}
